#!/bin/sh

if [ -z $1 ]; then
    BRANCH="master"
    REPO="seedstack.github.io"
    DIR="public"
else
    BRANCH="gh-pages"
    REPO="seedstack.github.io-${1}"
    DIR=${2}
fi

(
    cd ${DIR} || exit
    git init
    git config user.name "Travis-CI"
    git config user.email "travis@seedstack.org"
    git add .
    git commit -m "Website generated by Hugo"
    git push --force --quiet "https://${GITHUB_TOKEN}@github.com/seedstack/${REPO}" master:${BRANCH} > /dev/null 2>&1
)
