@startuml

package model.Order {

    class Order {
      Long orderId
      CustomerId customerId
      Date checkoutDate
      List<OrderItem> items
      double price
    }

    class OrderItem {
      Long orderItemId
      int quantity
      long productId
      double price
    }

}

Order"1" o-- "*"OrderItem

@enduml